[settings]
npm.bun = true
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]

[tools]
bun = "latest"
deno = "latest"
go = "latest"
node = "lts"
python = "latest"
ruby = "latest"
zig = "latest"
zls = "latest"
"npm:opencode-ai" = "latest"
"npm:@openai/codex" = "latest"
"npm:@anthropic-ai/claude-code" = "stable"
"npm:critique" = "latest" # https://github.com/remorses/critique
"pipx:pgcli" = { version = "latest", extras = "sshtunnel", uvx_args = "--with 'paramiko<4'" }
