[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]

[tools]
bun = "latest"
deno = "latest"
"github:sst/opencode" = "latest"
go = "latest"
node = "lts"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
python = "latest"
ruby = "latest"
zig = "latest"
zls = "latest"
